export interface WordEntry {
  word: string;
  hint: string;
}

export const WORDS: WordEntry[] = [
  { word: "ABAJO", hint: "dirección contraria al cielo" },
  { word: "ABEJA", hint: "insecto que hace miel y vive en colmenas" },
  { word: "ABRIR", hint: "acción para acceder a algo cerrado" },
  { word: "AGUJA", hint: "herramienta de costura muy fina" },
  { word: "ANTES", hint: "en un tiempo pasado" },
  { word: "ARENA", hint: "suelo fino de la playa" },
  { word: "ARBOL", hint: "planta con tronco, ramas y hojas" },
  { word: "AVION", hint: "transporte que vuela entre ciudades" },
  { word: "BANCO", hint: "asiento largo o entidad financiera" },
  { word: "BARCO", hint: "navega por el mar" },
  { word: "BARRO", hint: "mezcla húmeda de tierra y agua" },
  { word: "BLUSA", hint: "prenda de vestir femenina para el torso" },
  { word: "BRAVO", hint: "exclamación de aplauso o valentía" },
  { word: "BREVE", hint: "de muy corta duración" },
  { word: "BRUJA", hint: "personaje mágico de los cuentos de hadas" },
  { word: "BURRO", hint: "animal de carga parecido al caballo, pero más pequeño" },
  { word: "CABAL", hint: "exacto, completo, sin ninguna falta" },
  { word: "CALOR", hint: "sensación de temperatura muy alta" },
  { word: "CAMPO", hint: "terreno rural fuera de la ciudad" },
  { word: "CANAL", hint: "vía de agua artificial entre dos puntos" },
  { word: "CARTA", hint: "mensaje escrito en papel dentro de un sobre" },
  { word: "CASCO", hint: "protección que cubre la cabeza" },
  { word: "CEBRA", hint: "animal africano a rayas blancas y negras" },
  { word: "CERDO", hint: "animal que nos da el jamón" },
  { word: "CHICO", hint: "persona joven o de tamaño reducido" },
  { word: "CIELO", hint: "lo que ves al mirar hacia arriba" },
  { word: "CINCO", hint: "número entre cuatro y seis" },
  { word: "CLIMA", hint: "condiciones atmosféricas habituales de una región" },
  { word: "COBRA", hint: "serpiente venenosa conocida por su capucha" },
  { word: "COLOR", hint: "el rojo, el azul y el verde son ejemplos" },
  { word: "CORAL", hint: "organismo marino de vivos colores" },
  { word: "CORTE", hint: "acción de dividir algo con filo" },
  { word: "COSTA", hint: "donde el mar se encuentra con la tierra" },
  { word: "CREMA", hint: "producto suave que se aplica en la piel" },
  { word: "CUERO", hint: "piel curtida de animal usada en ropa y zapatos" },
  { word: "CUEVA", hint: "cavidad natural en la roca o la montaña" },
  { word: "CULTO", hint: "persona muy instruida o acto de adoración" },
  { word: "CURVA", hint: "línea que no es recta" },
  { word: "DANZA", hint: "movimiento artístico al ritmo de la música" },
  { word: "DEBUT", hint: "primera actuación o aparición pública" },
  { word: "DELTA", hint: "cuarta letra griega o desembocadura de un río" },
  { word: "DICHA", hint: "estado de felicidad plena" },
  { word: "DISCO", hint: "objeto redondo o álbum musical" },
  { word: "DOBLE", hint: "dos veces la cantidad original" },
  { word: "DOLOR", hint: "sensación desagradable física o emocional" },
  { word: "DUCHA", hint: "te usas para bañarte de pie" },
  { word: "DUELO", hint: "combate singular o periodo de luto" },
  { word: "DULCE", hint: "sabor característico del azúcar" },
  { word: "DUQUE", hint: "título nobiliario por debajo del rey" },
  { word: "ENERO", hint: "primer mes del año" },
  { word: "ERROR", hint: "equivocación o fallo involuntario" },
  { word: "FALSO", hint: "que no es verdadero ni auténtico" },
  { word: "FAVOR", hint: "ayuda desinteresada que se pide o se da" },
  { word: "FERIA", hint: "evento festivo con atracciones y puestos" },
  { word: "FIBRA", hint: "hilo natural o material resistente y flexible" },
  { word: "FINCA", hint: "terreno con casa en el campo" },
  { word: "FLOTA", hint: "conjunto de barcos o aviones" },
  { word: "FONDO", hint: "parte más profunda o trasera de algo" },
  { word: "FORMA", hint: "figura exterior de un objeto" },
  { word: "FRASE", hint: "conjunto de palabras con sentido completo" },
  { word: "FRESA", hint: "fruta roja pequeña y dulce" },
  { word: "FRENO", hint: "mecanismo para detener un vehículo" },
  { word: "FRITO", hint: "alimento cocinado en aceite caliente" },
  { word: "FRUTA", hint: "alimento dulce que da el árbol" },
  { word: "FUEGO", hint: "llamas, calor y luz" },
  { word: "FUROR", hint: "rabia intensa o gran éxito popular" },
  { word: "GALLO", hint: "macho de la gallina, canta al amanecer" },
  { word: "GAMBA", hint: "marisco de mar con cola" },
  { word: "GANSO", hint: "ave acuática grande prima del pato" },
  { word: "GARRA", hint: "uña fuerte y curvada de animal" },
  { word: "GARZA", hint: "ave de patas largas que vive cerca del agua" },
  { word: "GASTO", hint: "dinero que se desembolsa en algo" },
  { word: "GENIO", hint: "persona brillante o ser mágico de las lámpara" },
  { word: "GESTO", hint: "movimiento del cuerpo que expresa algo" },
  { word: "GLOBO", hint: "esfera de goma llena de aire o helio" },
  { word: "GOLFO", hint: "entrada de mar en la costa, o persona vaga" },
  { word: "GORRA", hint: "prenda para la cabeza con visera" },
  { word: "GRANO", hint: "semilla pequeña o protuberancia en la piel" },
  { word: "GRIPE", hint: "enfermedad viral con fiebre y cansancio" },
  { word: "GRUPO", hint: "conjunto de personas o cosas" },
  { word: "GRUTA", hint: "cueva pequeña, a veces artificial" },
  { word: "GUISO", hint: "plato cocinado lentamente con caldo" },
  { word: "GUSTO", hint: "sentido del sabor o preferencia personal" },
  { word: "HACHA", hint: "herramienta con filo para cortar madera" },
  { word: "HABER", hint: "verbo auxiliar fundamental del español" },
  { word: "HABLA", hint: "capacidad humana de expresarse oralmente" },
  { word: "HIELO", hint: "agua en estado sólido, muy fría" },
  { word: "HIENA", hint: "animal africano conocido por su risa" },
  { word: "HIMNO", hint: "canción oficial de un país o institución" },
  { word: "HONGO", hint: "organismo como la seta o el champiñón" },
  { word: "HONOR", hint: "dignidad y respeto ganados con buenas acciones" },
  { word: "HOTEL", hint: "donde te alojas cuando viajas" },
  { word: "HUECO", hint: "espacio vacío dentro de algo sólido" },
  { word: "HUEVO", hint: "lo pone la gallina" },
  { word: "HUMOR", hint: "estado de ánimo o capacidad de hacer reír" },
  { word: "ICONO", hint: "símbolo o imagen que representa algo" },
  { word: "IDEAL", hint: "exactamente como se desearía que fuese" },
  { word: "INDIO", hint: "persona de la India o nativo americano" },
  { word: "JAMON", hint: "embutido curado de cerdo, muy español" },
  { word: "JARRA", hint: "recipiente con asa para servir líquidos" },
  { word: "JAULA", hint: "estructura metálica para tener animales" },
  { word: "JOVEN", hint: "persona de poca edad" },
  { word: "JUEGO", hint: "actividad lúdica con reglas" },
  { word: "JULIO", hint: "séptimo mes del año" },
  { word: "JUNTO", hint: "al lado de, en compañía" },
  { word: "JUSTO", hint: "equitativo, o exactamente en el lugar correcto" },
  { word: "LARGO", hint: "de gran longitud de un extremo al otro" },
  { word: "LECHE", hint: "líquido blanco que produce la vaca" },
  { word: "LIMON", hint: "cítrico amarillo y muy ácido" },
  { word: "LLAMA", hint: "fuego visible, o animal andino pariente del camello" },
  { word: "LLANO", hint: "terreno completamente plano sin montañas" },
  { word: "LUNES", hint: "primer día de la semana laboral" },
  { word: "MADRE", hint: "progenitora femenina" },
  { word: "MANGA", hint: "parte del jersey que cubre el brazo" },
  { word: "MANGO", hint: "fruta tropical de color naranja por dentro" },
  { word: "MARCO", hint: "borde que rodea un cuadro o una foto" },
  { word: "MARZO", hint: "tercer mes del año" },
  { word: "MELON", hint: "fruta grande verde o amarilla, muy dulce en verano" },
  { word: "MISMO", hint: "idéntico, exactamente igual" },
  { word: "MONTE", hint: "elevación del terreno, menor que una montaña" },
  { word: "MOSCA", hint: "insecto volador negro y molesto" },
  { word: "MUNDO", hint: "el planeta Tierra o la totalidad de las cosas" },
  { word: "NEGRO", hint: "el color más oscuro, ausencia de luz" },
  { word: "NIEVE", hint: "agua congelada que cae del cielo en invierno" },
  { word: "NOBLE", hint: "de alta alcurnia o de gran generosidad" },
  { word: "NOCHE", hint: "periodo de oscuridad entre dos días" },
  { word: "NORTE", hint: "punto cardinal opuesto al sur" },
  { word: "ORDEN", hint: "disposición correcta y organizada de las cosas" },
  { word: "PALMA", hint: "árbol tropical o parte interna de la mano" },
  { word: "PAPEL", hint: "material fino para escribir o envolver" },
  { word: "PARED", hint: "superficie vertical que delimita una habitación" },
  { word: "PATIO", hint: "espacio abierto interior de una casa" },
  { word: "PECHO", hint: "parte frontal del torso humano" },
  { word: "PEDAL", hint: "palanca que se acciona con el pie" },
  { word: "PERRO", hint: "el mejor amigo del hombre" },
  { word: "PIANO", hint: "instrumento de teclas blancas y negras" },
  { word: "PISTA", hint: "superficie para practicar deporte, o una señal" },
  { word: "PLATA", hint: "metal precioso de color plateado" },
  { word: "PLAZA", hint: "espacio público abierto en una ciudad" },
  { word: "PLOMO", hint: "metal muy pesado y tóxico de color gris" },
  { word: "PODER", hint: "tener la capacidad o autoridad de hacer algo" },
  { word: "POETA", hint: "persona que escribe poesía" },
  { word: "POTRO", hint: "caballo joven" },
  { word: "PRADO", hint: "terreno con hierba donde pace el ganado" },
  { word: "QUESO", hint: "alimento lácteo sólido, hecho con leche cuajada" },
  { word: "RATON", hint: "pequeño roedor, también lo usas para el ordenador" },
  { word: "REINO", hint: "territorio gobernado por un rey o una reina" },
  { word: "RELOJ", hint: "instrumento que mide y muestra la hora" },
  { word: "RENTA", hint: "ingresos periódicos o precio del alquiler" },
  { word: "RIVAL", hint: "competidor o adversario" },
  { word: "ROBOT", hint: "máquina automatizada que imita acciones humanas" },
  { word: "ROCIO", hint: "gotitas de agua sobre las plantas al amanecer" },
  { word: "RUEDA", hint: "disco que gira, esencial en los vehículos" },
  { word: "SABIO", hint: "persona que posee gran sabiduría" },
  { word: "SALSA", hint: "condimento líquido o estilo musical caribeño" },
  { word: "SALUD", hint: "estado de bienestar físico y mental" },
  { word: "SAUCE", hint: "árbol de ramas largas y colgantes junto al agua" },
  { word: "SELLO", hint: "marca oficial o adhesivo que va en las cartas" },
  { word: "SIETE", hint: "número entre seis y ocho" },
  { word: "SIGLO", hint: "periodo de cien años" },
  { word: "SOBRE", hint: "recipiente de papel para meter una carta" },
  { word: "SOLAR", hint: "relativo al sol, o terreno sin edificar" },
  { word: "SUAVE", hint: "de textura agradable y delicada al tacto" },
  { word: "SUELO", hint: "superficie sobre la que caminamos" },
  { word: "TABLA", hint: "superficie plana y rectangular de madera" },
  { word: "TAREA", hint: "trabajo o ejercicio que hay que completar" },
  { word: "TARRO", hint: "recipiente de cristal con tapa para conservas" },
  { word: "TECHO", hint: "parte superior interior de una habitación" },
  { word: "TIGRE", hint: "felino salvaje más grande del mundo, con rayas" },
  { word: "TINTO", hint: "vino de color rojo oscuro" },
  { word: "TOCAR", hint: "entrar en contacto físico con algo" },
  { word: "TORNO", hint: "máquina para moldear materiales girando" },
  { word: "TUMOR", hint: "masa de tejido de crecimiento anormal" },
  { word: "VALOR", hint: "precio de algo, o valentía para afrontar algo" },
  { word: "VAPOR", hint: "agua en estado gaseoso" },
  { word: "VASCO", hint: "del País Vasco" },
  { word: "VENTA", hint: "acto de ceder algo a cambio de dinero" },
  { word: "VERDE", hint: "color de la hierba y los árboles" },
  { word: "VIEJO", hint: "de mucha edad, lo contrario de joven" },
  { word: "VIOLA", hint: "instrumento de cuerda o flor de color morado" },
  { word: "VISTA", hint: "sentido con el que percibimos la luz y los colores" },
  { word: "VUELO", hint: "desplazamiento por el aire" },
  { word: "ZUECO", hint: "calzado de madera o plástico duro" },
];

export function getRandomEntry(): WordEntry {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}

export function isValidGuess(word: string): boolean {
  return word.length === 5 && /^[A-Z]+$/.test(word);
}
